name: Exercise 1

on:
  push:

jobs:
  # cowsay-hey-there:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: install cowsay
  #     run: pip install cowsay
  #   - name: say things
  #     run: cowsay -c cheese -t 'hey there'
  # cowpy-hi-there:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: install cowpy
  #     run: pip install cowpy
  #   - name: say things
  #     run: cowpy -c tux hi there
  cowsay-on-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/scripts
        # working-directory: .
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: use the script
      # run: .github/scripts/cowsay_script.py
      run: ./cowsay_script.sh

